services:
  ropa_dormi_select_db:
    image: "postgres:18-trixie"
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ropaDormiSelectDB
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - ropa_dormi_select_db-data:/var/lib/postgresql
volumes:
  ropa_dormi_select_db-data:
